# GitCode API PAT，建议留空，用环境变量 GITCODE_TOKEN 覆盖
access_token = ""

# 默认 PR 状态 & 每页数量（单个仓库也可以覆盖）
states = ["merged", "open"]
per_page = 20
# 最大抓取页数（0 表示不限制）
max_pr_pages = 0
# PR 文件列表最大页数（0 表示不限制）
max_file_pages = 1
users = [
  "EMROF",
  "zhaoshenghua1",
  "ChaosJohn",
  "chongweizhi",
  "ovy",
  "jiyuan_99",
  "renyi43",
  "MinamiK",
  "xdst",
]

[[groups]]
name = "标准库团队"
users = [
  "EMROF",
  "zhaoshenghua1",
  "ChaosJohn",
  "chongweizhi",
  "ovy",
  "jiyuan_99",
  "renyi43",
  "MinamiK",
  "xdst",
]

[[repos]]
owner = "cangjie"
repo = "cangjie_runtime"

[[repos]]
owner = "cangjie"
repo = "cangjie_stdx"

[[repos]]
owner = "cangjie"
repo = "cangjie_test"
